### ISSUE TITLE
How to run testbench

### ISSUE THREAD

**Issue by iknowzxc** [wfjm/w11#15]
I use vivado 2016 and run following commands: 
```
cd $RETROBASE
 time nice tbrun -j 2 -norun -tag=viv -tee=tbrun_make_viv_bsim.log
 time nice tbrun -j 2 -nomake -tag=viv -tee=tbrun_run_viv_bsim.log
```

then 
```
#----------------------------------------
# t000 - tags: default,viv,comlib,cdata2byte
tbw tb_cdata2byte 2>&1 | tbfilt -tee tb_cdata2byte_bsim.log
real 0m0.021s   user 0m0.012s   sys 0m0.000s
tbfilt-I: no DONE seen; FAIL
tbrun-I: test FAILed with exit status 1,0
#----------------------------------------
# t001 - tags: default,viv,serport,rx
tbw tb_serport_uart_rx 2>&1 | tbfilt -tee tb_serport_uart_rx_bsim.log
real 0m0.020s   user 0m0.008s   sys 0m0.004s
tbfilt-I: no DONE seen; FAIL
tbrun-I: test FAILed with exit status 1,0
#----------------------------------------
# t002 - tags: default,viv,serport,rxtx
tbw tb_serport_uart_rxtx 2>&1 | tbfilt -tee tb_serport_uart_rxtx_bsim.log
real 0m0.023s   user 0m0.012s   sys 0m0.004s
tbfilt-I: no DONE seen; FAIL
tbrun-I: test FAILed with exit status 1,0
#----------------------------------------
```

and I don't know why, please help me

**Comment by wfjm** [comment]
First thing: look into `tb_cdata2byte_bsim.log` or any other step logfile, that should give information about the failure.

In a separate email you wrote that `tb_pdp11core_bsim_base.log` contained
```
Can't exec "tb_pdp11core": No such file or directory at '.../tool/bin/tbw' line 315, ...
failed to exec: No such file or directory at '.../tool/bin/tbw' line 315, ...
```
and that `tb_pdp11core` was properly build and is available under `w11a/tb`.

Reason behind this is most likely that `.` is not in your `PATH`.
The test bench scripts assume that the current working directory is in the `PATH`.
Unfortunately, that wasn't properly documented. I have updated [INSTALL.md](https://github.com/wfjm/w11/blob/master/doc/INSTALL.md) with commit 57934e3, the [Setup environment variables](https://github.com/wfjm/w11/blob/master/doc/INSTALL.md#user-content-envvar) now clearly states that `.` must be in `PATH`.
